### ISSUE TITLE
Upcoming changes to positions and image dimensions

### ISSUE THREAD

**Issue by fredli74** [fredli74/microtonic-skins#10]
Some controllers did not line up and I am adjusting them in the upcoming Microtonic 3.3.2 release.

**Comment by fredli74** [comment]
Alignments fixed in skin template (6377212d0633efbd91dc0bed2f6596825808cabb) and VintageTonic (33d90e1a54fcd318c0a3708db84ba039e11bf47f)

**Comment by fredli74** [comment]
@l4rs3rik I am messing with some controller pixel nudging in the next release and I am messing up your background print alignments a bit.

![2021-06-03_02h44_16](https://user-images.githubusercontent.com/6632456/120569144-9b12f400-c415-11eb-858d-9e1e8e86a156.png)

Is this something you wanna fix? In that case I can send you a new binary right away, are you running Mac or Windows?

**Comment by fredli74** [comment]
Finding more old odd alignment issues. I'm going to kick this bucket a bit more.

**Comment by l4rs3rik** [comment]
Yes I can fix that. I'm on Windows if you want to send me a VST dll.

**Comment by fredli74** [comment]
Ok, I noticed I had left some resources in incorrect dimensions. Which made some images rendered cut-off, and also made rescaling slightly worse due to rounding errors. I also found it hard to line up buttons and icons exactly when creating the Template with guidelines.

I have cleaned up what I found, and unfortunately, that means that the existing skins will look a lot worse unless updated as well. Here's a rundown of what I changed in Factory and VintageTonic skins.

`bluetogreenglasseggs_x2`, frames changed to 96x96, move everything left 2 pixels, then reduce space between each image by 4 pixels. The final image should be 96 x 768.
`whitetoblueglasseggs_x2`, frames changed to 96x96.

`displaybuttons_x2`, frames changed to 48x64, move everything down by 1 pixel, then increase space by 4.
`patchdisplay_x2`, dimensions changed to 304x52, move down 1 pixel.
`presetdisplay_x2`, dimensions changed to 568x52, move down 1 pixel.

`smallmenubutton_x2`, frames changed to 80x80, move everything 3 down and 2 right, then increase space by 4 pixels.

`channelnotes_x2`, frames changed to 64x32, move right by 36 pixels and 1 pixel up.
`channeltitles_x2`, frames changed to 64x32, move left by 2 pixels and 1 pixel down.

`matrixbackground_x2`, dimensions changed to 1120x488, expand the window frame by 16 pixels.
`matrixchannels_x2`, dimensions changed to 60x432, row height is now 52 pixels, shift each digit down by 2 pixels.
`matrixchoke_x2`, dimensions changed to 28x28, move right by 1 pixel and down by 1 pixel.
`matrixplayposition_x2`, dimensions changed to 56x8.

Then I had to do the following adjustments for the factory skin. Some because they were bad, some because coordinates were changed in the code.

`whitetobluematrixbutton_x2`, move everything down 3 pixels.
`whitetoredmutebutton_x2`, move everything down 3 pixels.

`whitetobluelargeroundbutton_x2`, move everything right 1 pixel.
`whitetoblueroundbutton_x2`, move everything up 1 pixel.
`whitetogreenroundbutton_x2`, this was not the same as blue in factory skin (I had to move everything up 2 pixels and 1 left).

`bluetogreensmalllanebutton_x2`, move everything down 1 pixel.
`whitetobluesmalllanebutton_x2`, move everything down 1 pixel.

`bluetogreenchannelbutton_x2`, move everything down 3 pixels.
`whitetobluechannelbutton_x2`, move everything down 3 pixels.
`whitetogreenchannelbutton_x2`, move everything down 3 pixels.

`buttonicons_x2`, script icon changed, please use the new one.
`tempo_x2`, dimensions changed to 256x32, move down by 4

Finally, I adjusted labels for all moved controls in the background image. Mainly choke, output, oscillator amount, noise filter q, stereo, velocity knobs, pattern chain, pattern step labels, pattern lane group spacing, master volume, stop and play buttons.

Sorry for doing these changes so late in the process.

**Comment by l4rs3rik** [comment]
Is this still an issue?
