### ISSUE TITLE
Wrong background color on tempo_x2 in Silverbox2

### ISSUE THREAD

**Issue by fredli74** [fredli74/microtonic-skins#23]
Hey @l4rs3rik,

Magnus noticed that the [tempo_x2.png](https://github.com/fredli74/microtonic-skins/blob/main/Microtonic%20Skins/Silverbox2/tempo_x2.png) image has the wrong background color. Is that something you can take a look at?

**Comment by l4rs3rik** [comment]
Yes. I fix.
